# Generated by Django 5.2.11 on 2026-02-17 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_processingstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_log', to='events.event')),
            ],
        ),
    ]
