# Generated by Django 5.2.11 on 2026-02-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_processedeventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingstate',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingstate',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingstate',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='processingstate',
            index=models.Index(fields=['next_retry_at'], name='idx_retry_schedule'),
        ),
    ]
