# Generated by Django 5.2.11 on 2026-02-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_processingstate_last_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingstate',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('queued', 'Queued'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('over', 'Over')], default='accepted', max_length=32),
        ),
    ]
